# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fs3cbS5b0m7IeW8dKJuS_hgm7S8GgpCN
"""

!pip install xgboost prophet shap torch scikit-learn --quiet

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import shap
import pickle
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from xgboost import XGBRegressor
from prophet import Prophet
import warnings
warnings.filterwarnings('ignore')

print("✅ All imports done.")

from google.colab import drive
drive.mount('/content/drive')

import gdown

# Télécharger directement depuis le lien Google Drive
file_id = "1gPhyZzl0Y-frq0lMx3M9JA49H2UkVMN1"
gdown.download(f"https://drive.google.com/uc?id={file_id}", "5g_dataset_scaled.csv", quiet=False)

df = pd.read_csv("5g_dataset_scaled.csv")
df = df.sort_values(['ue_id', 'timestamp']).reset_index(drop=True)

print(f"Shape    : {df.shape}")
print(f"UEs      : {df['ue_id'].nunique()}")
print(f"gNBs     : {df['gnb_id'].nunique()}")
print(f"Colonnes : {df.columns.tolist()}")

print(df.dtypes)
print()
print(df[['ue_name','gnb_name','ue_lat','ue_lon',
          'gnb_lat','gnb_lon','ue_dist_to_gnb_m']].head(10))
print()
print(df.describe())

fig, axes = plt.subplots(3, 1, figsize=(14, 10))
for ue in df['ue_id'].unique():
    sub = df[df['ue_id'] == ue]
    axes[0].plot(sub['timestamp'], sub['throughput_mbps'], alpha=0.4, linewidth=0.7)
    axes[1].plot(sub['timestamp'], sub['jitter_ms'],       alpha=0.4, linewidth=0.7)
    axes[2].plot(sub['timestamp'], sub['delay_ms'],        alpha=0.4, linewidth=0.7)

axes[0].set_title(f'Throughput (Mbps) — {df["ue_id"].nunique()} UEs, {df["gnb_id"].nunique()} gNBs')
axes[1].set_title('Jitter (ms)')
axes[2].set_title('Delay (ms)')
for ax in axes:
    ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("eda_qos_scaled.png", dpi=150)
plt.show()

fig2, ax2 = plt.subplots(1, 3, figsize=(14, 4))
for i, metric in enumerate(['throughput_mbps', 'jitter_ms', 'delay_ms']):
    df.groupby('gnb_name')[metric].mean().plot(
        kind='bar', ax=ax2[i], color=['#534AB7','#1D9E75','#D85A30'])
    ax2[i].set_title(f'Moyenne {metric} par gNB')
    ax2[i].tick_params(axis='x', rotation=20)
    ax2[i].grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("eda_by_gnb.png", dpi=150)
plt.show()
print("✅ EDA done.")

df = df.sort_values(['ue_id', 'timestamp'])

for col in ['throughput_mbps', 'jitter_ms', 'sinr_dl_db', 'packet_loss_ratio']:
    df[f'{col}_roll3'] = df.groupby('ue_id')[col].transform(
        lambda x: x.rolling(3, min_periods=1).mean())
    df[f'{col}_roll5'] = df.groupby('ue_id')[col].transform(
        lambda x: x.rolling(5, min_periods=1).mean())
    df[f'{col}_lag1']  = df.groupby('ue_id')[col].transform(
        lambda x: x.shift(1))
    df[f'{col}_lag3']  = df.groupby('ue_id')[col].transform(
        lambda x: x.shift(3))

df = df.dropna().reset_index(drop=True)
print(f"✅ Shape après feature engineering: {df.shape}")

NON_FEATURES = [
    'timestamp', 'ue_id', 'gnb_id',
    'ue_name', 'gnb_name',
    'jitter_ms', 'throughput_mbps', 'delay_ms'
]

FEATURE_COLS = [
    c for c in df.columns
    if c not in NON_FEATURES and df[c].dtype in ['float64','int64']
]

print(f"Features utilisées ({len(FEATURE_COLS)}):")
print(FEATURE_COLS)

X            = df[FEATURE_COLS]
y_jitter     = df['jitter_ms']
y_throughput = df['throughput_mbps']

X_train, X_test, y_j_train, y_j_test = train_test_split(
    X, y_jitter,     test_size=0.2, random_state=42, shuffle=False)
_,       _,      y_t_train, y_t_test = train_test_split(
    X, y_throughput, test_size=0.2, random_state=42, shuffle=False)

print(f"\n✅ Train: {len(X_train)} | Test: {len(X_test)}")

xgb_jitter = XGBRegressor(
    n_estimators=400, max_depth=6, learning_rate=0.05,
    subsample=0.8, colsample_bytree=0.8, random_state=42, n_jobs=-1
)
xgb_jitter.fit(X_train, y_j_train,
               eval_set=[(X_test, y_j_test)], verbose=100)

y_pred_j = xgb_jitter.predict(X_test)

rmse_j = np.sqrt(mean_squared_error(y_j_test, y_pred_j))
mae_j  = mean_absolute_error(y_j_test, y_pred_j)
r2_j   = r2_score(y_j_test, y_pred_j)

print("\n📊 XGBoost — Jitter (ms):")
print(f"  RMSE : {rmse_j:.4f} ms")
print(f"  MAE  : {mae_j:.4f} ms")
print(f"  R²   : {r2_j:.4f}")

pred_jitter_df = X_test.copy().reset_index(drop=True)
df_test_subset = df.iloc[X_test.index].reset_index(drop=True)

pred_jitter_df['timestamp'] = df_test_subset['timestamp'].values
pred_jitter_df['ue_id']     = df_test_subset['ue_id'].values
pred_jitter_df['ue_name']   = df_test_subset['ue_name'].values
pred_jitter_df['gnb_name']  = df_test_subset['gnb_name'].values
pred_jitter_df['ue_lat']    = df_test_subset['ue_lat'].values
pred_jitter_df['ue_lon']    = df_test_subset['ue_lon'].values
pred_jitter_df['y_true']    = y_j_test.values
pred_jitter_df['y_pred']    = y_pred_j

pred_jitter_df.to_csv("predicted_jitter.csv", index=False)

with open("xgboost_jitter.pkl", "wb") as f:
    pickle.dump(xgb_jitter, f)

print("✅ predicted_jitter.csv sauvegardé")
print("✅ xgboost_jitter.pkl sauvegardé")
print(f"   Lignes : {len(pred_jitter_df)}")

plt.figure(figsize=(14, 4))
plt.plot(y_j_test.values[:300], label='Réel',   alpha=0.8)
plt.plot(y_pred_j[:300],        label='Prédit', alpha=0.8)
plt.title(f"XGBoost Jitter — RMSE={rmse_j:.4f} ms | MAE={mae_j:.4f} ms | R²={r2_j:.4f}")
plt.xlabel("Échantillon")
plt.ylabel("Jitter (ms)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig("xgb_jitter_prediction.png", dpi=150)
plt.show()

explainer   = shap.TreeExplainer(xgb_jitter)
shap_values = explainer.shap_values(X_test.iloc[:500])
shap.summary_plot(shap_values, X_test.iloc[:500], plot_type="bar", show=False)
plt.title("SHAP — Importance features (Jitter)")
plt.savefig("shap_jitter_importance.png", bbox_inches='tight')
plt.show()
print("✅ SHAP sauvegardé")

xgb_throughput = XGBRegressor(
    n_estimators=400, max_depth=6, learning_rate=0.05,
    subsample=0.8, colsample_bytree=0.8, random_state=42, n_jobs=-1
)
xgb_throughput.fit(X_train, y_t_train,
                   eval_set=[(X_test, y_t_test)], verbose=100)

y_pred_t = xgb_throughput.predict(X_test)

rmse_t = np.sqrt(mean_squared_error(y_t_test, y_pred_t))
mae_t  = mean_absolute_error(y_t_test, y_pred_t)
r2_t   = r2_score(y_t_test, y_pred_t)

print("\n📊 XGBoost — Throughput (Mbps):")
print(f"  RMSE : {rmse_t:.4f} Mbps")
print(f"  MAE  : {mae_t:.4f} Mbps")
print(f"  R²   : {r2_t:.4f}")

with open("xgboost_throughput.pkl", "wb") as f:
    pickle.dump(xgb_throughput, f)
print("✅ xgboost_throughput.pkl sauvegardé")

WINDOW      = 20
HORIZONS    = [1, 3, 5]
scaler_lstm = StandardScaler()

def build_sequences(df, target_col, window, horizon):
    all_X, all_y = [], []
    for ue in df['ue_id'].unique():
        sub    = df[df['ue_id'] == ue].sort_values('timestamp')
        series = scaler_lstm.fit_transform(sub[[target_col]].values)
        for i in range(len(series) - window - horizon):
            all_X.append(series[i : i + window])
            all_y.append(series[i + window + horizon - 1])
    return np.array(all_X), np.array(all_y)

print(f"✅ WINDOW={WINDOW} | HORIZONS={HORIZONS}")
print(f"✅ build_sequences définie")

class LSTMRegressor(nn.Module):
    def __init__(self, input_size=1, hidden=64, num_layers=2, dropout=0.2):
        super().__init__()
        self.lstm = nn.LSTM(input_size, hidden, num_layers,
                            batch_first=True, dropout=dropout)
        self.fc   = nn.Linear(hidden, 1)

    def forward(self, x):
        out, _ = self.lstm(x)
        return self.fc(out[:, -1, :])

print("✅ Architecture LSTM définie.")

results_lstm = {}

for horizon in HORIZONS:
    print(f"\n{'='*45}")
    print(f"🔁 LSTM — horizon t+{horizon}")

    all_X, all_y = build_sequences(df, 'throughput_mbps', WINDOW, horizon)

    split = int(0.8 * len(all_X))
    X_tr  = torch.tensor(all_X[:split], dtype=torch.float32)
    y_tr  = torch.tensor(all_y[:split], dtype=torch.float32)
    X_te  = torch.tensor(all_X[split:], dtype=torch.float32)
    y_te  = torch.tensor(all_y[split:], dtype=torch.float32)

    model     = LSTMRegressor()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    loss_fn   = nn.MSELoss()

    for epoch in range(40):
        model.train()
        optimizer.zero_grad()
        loss = loss_fn(model(X_tr), y_tr)
        loss.backward()
        optimizer.step()
        if (epoch + 1) % 10 == 0:
            print(f"  Epoch {epoch+1}/40 | Loss: {loss.item():.5f}")

    model.eval()
    with torch.no_grad():
        preds = model(X_te).numpy().flatten()
        truth = y_te.numpy().flatten()

    rmse_lstm = np.sqrt(mean_squared_error(truth, preds))
    results_lstm[f't+{horizon}'] = rmse_lstm
    print(f"  ✅ RMSE t+{horizon}: {rmse_lstm:.4f}")
    torch.save(model.state_dict(), f"lstm_throughput_t{horizon}.pt")

print("\n📊 Résumé LSTM:")
for k, v in results_lstm.items():
    print(f"  {k}: RMSE = {v:.4f}")

print(f"📈 Prophet — {df['ue_id'].nunique()} UEs × 2 métriques")
forecast_all = []
base = pd.Timestamp("2024-01-01")

for ue in df['ue_id'].unique():
    sub       = df[df['ue_id'] == ue].sort_values('timestamp').copy()
    sub['ds'] = base + pd.to_timedelta(sub['timestamp'], unit='s')

    for metric in ['jitter_ms', 'throughput_mbps']:
        prophet_df = sub[['ds', metric]].rename(columns={metric: 'y'})
        m = Prophet(yearly_seasonality=False,
                    weekly_seasonality=False,
                    daily_seasonality=True)
        m.fit(prophet_df)
        future   = m.make_future_dataframe(periods=50, freq='s')
        forecast = m.predict(future)
        forecast['ue_id']    = ue
        forecast['ue_name']  = sub['ue_name'].iloc[0]
        forecast['gnb_name'] = sub['gnb_name'].iloc[0]
        forecast['metric']   = metric
        forecast_all.append(
            forecast[['ds','ue_id','ue_name','gnb_name',
                       'metric','yhat','yhat_lower','yhat_upper']]
        )
    print(f"  ✅ UE {ue} — {sub['ue_name'].iloc[0]}")

forecast_ci = pd.concat(forecast_all, ignore_index=True)
forecast_ci.to_csv("forecast_ci.csv", index=False)
print(f"\n✅ forecast_ci.csv — {len(forecast_ci)} lignes")

sub1       = df[df['ue_id'] == 1].sort_values('timestamp').copy()
base       = pd.Timestamp("2024-01-01")
sub1['ds'] = base + pd.to_timedelta(sub1['timestamp'], unit='s')
ue1_name   = sub1['ue_name'].iloc[0]

prophet_plot = sub1[['ds','jitter_ms']].rename(columns={'jitter_ms':'y'})
m_plot = Prophet(yearly_seasonality=False,
                 weekly_seasonality=False,
                 daily_seasonality=True)
m_plot.fit(prophet_plot)
fc_plot = m_plot.predict(
    m_plot.make_future_dataframe(periods=50, freq='s'))

fig = m_plot.plot(fc_plot)
plt.title(f"Prophet — Jitter Forecast (UE1 · {ue1_name})")
plt.savefig("prophet_jitter_ue1.png", dpi=150)
plt.show()

results_summary = pd.DataFrame([
    {
        "Modèle" : "XGBoost",
        "Cible"  : "jitter_ms",
        "RMSE"   : round(rmse_j, 4),
        "MAE"    : round(mae_j,  4),
        "R²"     : round(r2_j,   4),
        "Unité"  : "ms"
    },
    {
        "Modèle" : "XGBoost",
        "Cible"  : "throughput_mbps",
        "RMSE"   : round(rmse_t, 4),
        "MAE"    : round(mae_t,  4),
        "R²"     : round(r2_t,   4),
        "Unité"  : "Mbps"
    },
    {
        "Modèle" : "LSTM",
        "Cible"  : "throughput (t+1)",
        "RMSE"   : round(results_lstm['t+1'], 4),
        "MAE"    : None,
        "R²"     : None,
        "Unité"  : "normalisé"
    },
    {
        "Modèle" : "LSTM",
        "Cible"  : "throughput (t+3)",
        "RMSE"   : round(results_lstm['t+3'], 4),
        "MAE"    : None,
        "R²"     : None,
        "Unité"  : "normalisé"
    },
    {
        "Modèle" : "LSTM",
        "Cible"  : "throughput (t+5)",
        "RMSE"   : round(results_lstm['t+5'], 4),
        "MAE"    : None,
        "R²"     : None,
        "Unité"  : "normalisé"
    },
    {
        "Modèle" : "Prophet",
        "Cible"  : "jitter + throughput",
        "RMSE"   : None,
        "MAE"    : None,
        "R²"     : None,
        "Unité"  : "IC 80% (yhat_lower/yhat_upper)"
    },
])

print("=" * 65)
print("📊 RÉSULTATS FINAUX — DSO1.1 QoS Estimation")
print(f"   Dataset: {df['ue_id'].nunique()} UEs | {df['gnb_id'].nunique()} gNBs | Tunis")
print("=" * 65)
print(results_summary.to_string(index=False))

results_summary.to_csv("results_summary.csv", index=False)
print("\n✅ results_summary.csv sauvegardé")

from google.colab import files

output_files = [
    "results_summary.csv",
    "predicted_jitter.csv",
    "forecast_ci.csv",
    "xgboost_jitter.pkl",
    "xgboost_throughput.pkl",
    "lstm_throughput_t1.pt",
    "lstm_throughput_t3.pt",
    "lstm_throughput_t5.pt",
    "eda_qos_scaled.png",
    "eda_by_gnb.png",
    "xgb_jitter_prediction.png",
    "shap_jitter_importance.png",
    "prophet_jitter_ue1.png",
]

for f_name in output_files:
    try:
        files.download(f_name)
        print(f"  ⬇️  {f_name}")
    except Exception as e:
        print(f"  ⚠️  {f_name} — {e}")